### ISSUE TITLE
保存样式按钮问题

### ISSUE THREAD

**Issue by annder** [yesccx/ydoc#2]
![image](https://user-images.githubusercontent.com/12369444/87904372-bcceeb00-ca90-11ea-9927-5fd6cceaf7c0.png)

保存按钮的下拉框与按钮没对齐。

Chrome version: 83.0.4103.116
屏幕分辨率: 1920 x 1080

**Comment by annder** [comment]
补充：
![TIM图片20200720135913](https://user-images.githubusercontent.com/12369444/87904634-4ed6f380-ca91-11ea-8279-195b7debeb2b.png)

**Comment by yesccx** [comment]
感谢反馈，问题已解决，下个版本一起更新发布。
